version: "3.8"

networks:
  cafeteria:
    driver: bridge

services:
  database:
    container_name: database
    image: cafeteria/database
    build:
      context: database
      dockerfile: Dockerfile
    volumes:
      - database-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=teste123
      - POSTGRES_DB=cafeteria
      - PGDATA=/var/lib/postgresql/data/cafeteria

volumes:
  database-storage:
