version: "3.8"

networks:
  cafeteria:
    driver: bridge

services:
  database:
    container_name: database
    image: cafeteria/database
    build:
      context: database
      dockerfile: Dockerfile
    volumes:
      - database-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=teste123
      - POSTGRES_DB=cafeteria
      - PGDATA=/var/lib/postgresql/data/cafeteria
    networks:
      - cafeteria

  backend:
    container_name: backend
    image: cafeteria/backend
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=/usr/src/app
    entrypoint:  [
      "python",
      "-Xfrozen_modules=off",
      "-m", "debugpy",
      "--listen", "0.0.0.0:5678",
      "-m", "app",
      "--wait-for-client",
      "--multiprocess",
      "-m", "flask",
      "run",
      "-h", "0.0.0.0",
      "-p", "5000"
    ]
    ports:
      - 5678:5678
    networks:
      - cafeteria
    depends_on:
      - database

  frontend:
    container_name: frontend
    build:
      context: frontend/
      dockerfile: Dockerfile
      target: dev
    image: cafeteria/frontend
    volumes:
      - ./frontend/image:/app/
    depends_on:
      - backend
    networks:
      - cafeteria
    stdin_open: true

  proxy:
    container_name: proxy
    image: cafeteria/proxy
    build:
      context: proxy
      dockerfile: Dockerfile
    networks:
      - cafeteria
    depends_on:
      - backend
      - frontend
    ports:
      - 80:80
      - 443:443

volumes:
  database-storage:
